services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - dev-mail
    links:
      - db
    volumes:
      - .:/var/www:cached
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=mein-schulessen
  db:
    image: mariadb:11.8@sha256:8164f184d16c30e2f159e30518113667b796306dff0fe558876ab1ff521a682f
    restart: always
    volumes:
      - ./mysql11:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: mein-schulessen
    ports:
      - "8889:3306"
  testdb:
    image: mariadb:11.8@sha256:8164f184d16c30e2f159e30518113667b796306dff0fe558876ab1ff521a682f
    restart: always
    volumes:
      - ./mysql_test11:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: mein-schulessen-test
    ports:
      - "8887:3306"
networks:
  dev-mail:
    external: true
