<?php

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class FormTypeResultExtension
 * @package App\Form\Extension
 */
class FormTypeResultExtension extends AbstractTypeExtension
{

    /**
     * Return the class of the type being extended.
     * @return string[]
     */
    public static function getExtendedTypes(): iterable
    {
        // return FormType::class to modify (nearly) every field in the system
        return [FormType::class];
    }

    /**
     * @param FormView       $view
     * @param FormInterface  $form
     * @param array|string[] $options
     */
    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
        if (isset($options['last_result'])) {
            $view->vars['last_result'] = $options['last_result'];
        }
        if (isset($options['master_data_question'])) {
            $view->vars['master_data_question'] = $options['master_data_question'];
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefined(['last_result', 'master_data_question', 'csrf_protection']);
    }
}
